stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building project..."
    - mkdir build
    - echo "Build output" > build/output.txt
  artifacts:
    paths:
      - build/

test-job:
  stage: test
  script:
    - echo "testing Project..."
    - cat build/output.txt
  dependencies:
    - build-job
deploy-job:
  stage: deploy
  script:
    - echo "Deploying project..."
    - echo "Deployment Complete"
