stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building project..."
    - mkdir output
    - echo "Build output" > output/file.txt
  artifacts:
    paths:
      - output/

test-job:
  stage: test
  script:
    - echo "testing Project..."
    - cat hello.txt

deploy-job:
  stage: deploy
  script:
    - echo "Deploying project..."
