stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building project..."
    - ls -la

test-job:
  stage: test
  script:
    - echo "testing Project..."
    - cat hello.txt

deploy-job:
  stage: deploy
  script:
    - echo "Deploying project..."
    - cat missingfile.txt
